# Generated by Django 5.2.12 on 2026-04-04 05:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investments', 'Investments'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('groceries', 'Groceries'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('other', 'Other')], db_index=True, max_length=30)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags', max_length=255)),
            ],
            options={
                'db_table': 'financial_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
