# Generated by Django 5.2.12 on 2026-04-04 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['user', 'type'], name='financial_r_user_id_2c3395_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['user', 'date'], name='financial_r_user_id_497cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['user', 'category'], name='financial_r_user_id_f365e5_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['date', 'type'], name='financial_r_date_934439_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['user', 'is_deleted'], name='financial_r_user_id_f7c5f1_idx'),
        ),
    ]
